### PR TITLE
Converted images in assets/images to .webp format

### LINKED ISSUE #8: Use Next Gen Image Formats
images in `/assets` folder should use next-gen image format to help users save their mobile data usage

can consider using the `WebP` image format

A balance between small image size and high image quality
- image size should not be more than 200KB
- Image should look good on a 1920x1080 monitor

### PR DESCRIPTION
**Pull request by aswin2108**
Fixes #8 
@kachun333 
I have converted all the images in assets/images to webp format. Very few are above 200kb. 

### Additional Notes
Dont merge this, give me a bit more time, finding ways to reduce the ones above 200kb. 
Really sorry for the delay, some university exams and some term ending works were there.

### CODE REVIEW

**Comment by kachun333** [comment]
No worries @aswin2108 , take ur time

**Comment by aswin2108** [comment]
@kachun333 I request you to merge it!
I tried to take it below 200kb, but 4 are staying at 219,204,337,235 kb! The reason for this delay was some university exams and in the end, I had to convert some files one by one to get it below 200kb! Still, these 4 were in 200+
You can also try it, but I have tried with almost every tool available on the web.

**Comment by kachun333** [comment]
@aswin2108 alright will look into them tmr. Thanks!

**Review by kachun333 — APPROVED** [review]
thanks @aswin2108

**Comment by kachun333** [comment]
@aswin2108 , can you open another PR to change the imports, currently the image src link is broken.

1. search all normal imports and change `png`/`jpg` to `webp`
example: 
```typescript
import Logo from "assets/images/logo.png"; // old, using png ❌ 
import Logo from "assets/images/logo.webp"; // new, change to use webp you created ✅ 

import VideosImage from "assets/images/banner/videos.jpg";  // old, using jpg ❌ 
import VideosImage from "assets/images/banner/videos.webp"; // new, using webp you created ✅ 
```

also add module declaration, so that ts won't complain when trying to import webp
```ts
// at types\index.d.ts
// old code ❌ 

/* TODO: use WebP images instead of PNG/JPG */
declare module "*.png";
declare module "*.jpg";
```

```ts
// at types\index.d.ts
// new code, allow import webp image only ✅ 
declare module "*.webp";
```

2.  at `src\pages\graduates\graduates.constants.ts`, replace all `.jpg` to `.webp`
example:
```
import("assets/images/graduates/Chan Ka Chun.jpg") // old import, using jpg ❌ 
import("assets/images/graduates/Chan Ka Chun.webp") // new, using webp you created ✅ 
```

**Comment by aswin2108** [comment]
@kachun333 Yeah would love to do that!

**Pull request merged**
